name: Build and Publish PDF

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: osmnx-paper.tex

      - name: Publish PDF
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: "osmnx-paper.pdf"
          target: "~/public_html/share"
          use_insecure_cipher: true
